<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ClubCraft.SagaOrchestrator-73c0d172-4828-43aa-a0e0-359f86ca43dd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.2.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Sagas\ClubCraft.BuildingBlocks.Sagas\ClubCraft.BuildingBlocks.Sagas.csproj" />
  </ItemGroup>
</Project>
